namespace ResourceProperties {
    public enum ResourceProperty {
        //HARDNESS
        HARD,
        SOFT,
        //COLOR
        YELLOW,
        RED,
        BLUE,
        GRAY,
        GREEN,
        MAGENTA,
        RAINBOW,
        //TYPE
        SEED,
        FRUIT,
        SLUDGE,
        FUNGUS,
        MINERAL,
        ROOT,
        //RARITY
        COMMON,
        RARE,
        EPIC,
        LEGENDARY,
        //TASTE
        SPICY,
        SOUR,
        SWEET,
        SAVORY
    }
}